### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by maurerle** [OFFIS-DAI/mango#101]
Hi, I would really like to have a new release with the latest changes from development!

Is there anything which is missing currently?

**Comment by rcschrg** [comment]
Hey Florian,

Actually, there will be many changes very soon, some of which will break parts of the API. 

These changes will be made to align mango-python to Mango.jl. We will introduce some of the newer Mango.jl features and simplify the API in some regards, including the API break that we won't start the container on creation anymore. Furthermore, the external coupling container will change dramatically. And we plan a huge documentation overhaul to ensure doc example correctness like we did in Mango.jl.

However, this will happen mostly in October and November, so we can release a new version now imo.

**Comment by rcschrg** [comment]
Should be there when https://github.com/OFFIS-DAI/mango/actions/runs/10832640139 finishes.

**Comment by rcschrg** [comment]
Here we go: https://pypi.org/project/mango-agents/1.2.0/
