### ISSUE TITLE
High memory usage of as_agent_process function since mango 2.x

### ISSUE THREAD

**Issue by maurerle** [OFFIS-DAI/mango#139]
Of course switching the multiprocessing `get_start_method` from `fork` to `spawn` changes a few things.
However, I would like to have a more lightweight way to create new processes without copying the whole process memory another time.

`mprof run -M assume -s example_03 -c base_case_2019 -p`
`mprof plot`

using mprof to profile the simulation allocates more and more resources until it goes OOM

![image](https://github.com/user-attachments/assets/527ffba3-a711-417e-b870-399f0161db2e)

With mango 1.x this did start the simulation in less than 2 seconds:

![image](https://github.com/user-attachments/assets/fc33f8d6-53c8-4205-9819-06064f04afad)

Note that this of course only happens when using the multiprocessing mode (as_agent_process) with mango 2.x

Do you have an idea on that @rcschrg?

**Comment by rcschrg** [comment]
Regarding the time, "spawn" is way slower there is nothing we can do here. Regarding the memory, can you link to your example you are running?

And would switching to fork solve the issue? Then we could add a settings dics for mp.py and users would be able to choose fork again, which might be favorable for a lot of users, I changed the default to spawn (together with all this serializing and fp logic) to support macOS (and maybe Windows at some point).

**Comment by maurerle** [comment]
Setting `self._ctx = get_context("fork")` does indeed solve this here:

![image](https://github.com/user-attachments/assets/2e293463-b91d-4145-8f22-631a9858946c)

Though this gives a `DeprecationWarning: This process (pid=180925) is multi-threaded, use of fork() may lead to deadlocks in the child.` for each as_agent_process usage - these are ignored in #140 during the creation.

Using the `forkserver` method did not help in my case, but as long as fork is available on linux, that is fine for me.
