### ISSUE TITLE
Adding new agents to existing container

### ISSUE THREAD

**Issue by juergensi** [OFFIS-DAI/mango#141]
Is there a way to add and run newly created role based agents to an already activated container? It seems that agent.start() is only executed after the container is activated. Is there an alternative way to do this?

The feature would be helpful to create a simulation which periodically creates agents.

**Comment by rcschrg** [comment]
Hi @juergensi,

which version do you use? Registration of agents after activation is something we implemented like one month ago. And it should work in >= 2.1.1.

**Comment by juergensi** [comment]
Thanks Rico the version installed was 2.1.0 so  a bit too early. With the updated version it looks pretty good.

**Comment by rcschrg** [comment]
Great! I close this issue then :)
