### ISSUE TITLE
many file descriptors

### ISSUE THREAD

**Issue by Ellariel** [OFFIS-DAI/mango#70]
Hi,
when I create one agent in the system 6 file descriptors are reserved. Could you please advise if I do it correctly and if so, is there any way to control descriptors in case there is a limit in the system (I am using a server that has a limit per user). Thanks!!!
![image](https://github.com/OFFIS-DAI/mango/assets/28444339/d3309c7f-6e64-446a-803d-aa79d1b3706d)
An example https://github.com/Ellariel/mangotest/

**Comment by rcschrg** [comment]
Hello @Ellariel, yeah this is correct. Every agent has its own scheduler, which contains a process executor for scheduling process tasks, this executor seems to open the file descriptors on initialization. I agree that this is a rather bad behavior. I changed this behavior such that the fd are only opened if process tasks are created, see PR #71
